workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.example.flutter_toast_catalog"
      flutter: "3.19.6"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter (Debug)
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.flutteryaml
      vars:
        APP_ID: 1111111111 # <-- Put your APP ID here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

cache:
  # Cache Flutter dependencies and Gradle cache for Android
  cache_paths:
    - $HOME/.pub-cache
    - $HOME/.gradle
    - build/**/intermediates
    - build/**/outputs
    
  # Cache Flutter, CocoaPods, and derived data for iOS
  ios_cache_paths:
    - $HOME/.pub-cache
    - ios/.symlinks
    - ios/Pods
    - ios/Flutter/Flutter.framework
    - build/ios
